"use client";

import React from "react";
import Table from "@/app/components/table";

const page = () => {
  const headers: string[] = [
    "Deck Name",
    "Boolean",
    "E1",
    "E2",
    "E3",
    "E4",
    "E5",
    "E6",
    "E7",
    "E8",
    "E9",
    "E10",
  ];

  const data = [
    {
      id: 1,
      "Deck Name": "Deck 1",
      Boolean: true,
      E1: { title: "Temperature", value: 100, arrowUp: true },
      E2: { title: "Pressure", value: 200, arrowUp: false },
      E3: { title: "Humidity", value: 300, arrowUp: true },
      E4: { title: "Wind Speed", value: 400, arrowUp: false },
      E5: { title: "Precipitation", value: 500, arrowUp: true },
      E6: { title: "Visibility", value: 600, arrowUp: false },
      E7: { title: "UV Index", value: 700, arrowUp: true },
      E8: { title: "Solar Radiation", value: 800, arrowUp: false },
      E9: { title: "Temperature", value: 900, arrowUp: true },
      E10: { title: "Pressure", value: 1000, arrowUp: false },
    },
    {
      id: 2,
      "Deck Name": "Deck 2",
      Boolean: false,
      E1: { title: "Temperature", value: 150, arrowUp: false },
      E2: { title: "Pressure", value: 250, arrowUp: true },
      E3: { title: "Humidity", value: 350, arrowUp: false },
      E4: { title: "Wind Speed", value: 450, arrowUp: true },
      E5: { title: "Precipitation", value: 550, arrowUp: false },
      E6: { title: "Visibility", value: 650, arrowUp: true },
      E7: { title: "UV Index", value: 750, arrowUp: false },
      E8: { title: "Solar Radiation", value: 850, arrowUp: true },
      E9: { title: "Temperature", value: 950, arrowUp: false },
      E10: { title: "Pressure", value: 1050, arrowUp: true },
    },
    {
      id: 3,
      "Deck Name": "Is it nice out?",
      Boolean: true,
      E1: { title: "Temperature", value: 200, arrowUp: true },
      E2: { title: "Pressure", value: 300, arrowUp: false },
      E3: { title: "Humidity", value: 400, arrowUp: true },
      E4: { title: "Wind Speed", value: 500, arrowUp: false },
      E5: { title: "Precipitation", value: 600, arrowUp: true },
      E6: { title: "Visibility", value: 700, arrowUp: false },
      E7: { title: "UV Index", value: 800, arrowUp: true },
      E8: { title: "Solar Radiation", value: 900, arrowUp: false },
      E9: { title: "Temperature", value: 1000, arrowUp: true },
      E10: { title: "Pressure", value: 1100, arrowUp: false },
    },
    {
      id: 4,
      "Deck Name": "Running weather",
      Boolean: true,
      E1: { title: "Temperature", value: 200, arrowUp: true },
      E2: { title: "Pressure", value: 300, arrowUp: false },
      E3: { title: "Humidity", value: 400, arrowUp: true },
      E4: { title: "Wind Speed", value: 500, arrowUp: false },
      E5: { title: "Precipitation", value: 600, arrowUp: true },
      E6: { title: "Visibility", value: 700, arrowUp: false },
      E7: { title: "UV Index", value: 800, arrowUp: true },
      E8: { title: "Solar Radiation", value: 900, arrowUp: false },
      E9: { title: "Temperature", value: 1000, arrowUp: true },
      E10: { title: "Pressure", value: 1100, arrowUp: false },
    },
    {
      id: 5,
      "Deck Name": "Deck 5",
      Boolean: false,
      E1: { title: "Temperature", value: 120, arrowUp: false },
      E2: { title: "Pressure", value: 220, arrowUp: true },
      E3: { title: "Humidity", value: 320, arrowUp: false },
      E4: { title: "Wind Speed", value: 420, arrowUp: true },
      E5: { title: "Precipitation", value: 520, arrowUp: false },
      E6: { title: "Visibility", value: 620, arrowUp: true },
      E7: { title: "UV Index", value: 720, arrowUp: false },
      E8: { title: "Solar Radiation", value: 820, arrowUp: true },
      E9: { title: "Temperature", value: 920, arrowUp: false },
      E10: { title: "Pressure", value: 1020, arrowUp: true },
    },
    {
      id: 6,
      "Deck Name": "Deck 6",
      Boolean: true,
      E1: { title: "Temperature", value: 140, arrowUp: true },
      E2: { title: "Pressure", value: 240, arrowUp: false },
      E3: { title: "Humidity", value: 340, arrowUp: true },
      E4: { title: "Wind Speed", value: 440, arrowUp: false },
      E5: { title: "Precipitation", value: 540, arrowUp: true },
      E6: { title: "Visibility", value: 640, arrowUp: false },
      E7: { title: "UV Index", value: 740, arrowUp: true },
      E8: { title: "Solar Radiation", value: 840, arrowUp: false },
      E9: { title: "Temperature", value: 940, arrowUp: true },
      E10: { title: "Pressure", value: 1040, arrowUp: false },
    },
    {
      id: 7,
      "Deck Name": "Deck 7",
      Boolean: false,
      E1: { title: "Temperature", value: 160, arrowUp: false },
      E2: { title: "Pressure", value: 260, arrowUp: true },
      E3: { title: "Humidity", value: 360, arrowUp: false },
      E4: { title: "Wind Speed", value: 460, arrowUp: true },
      E5: { title: "Precipitation", value: 560, arrowUp: false },
      E6: { title: "Visibility", value: 660, arrowUp: true },
      E7: { title: "UV Index", value: 760, arrowUp: false },
      E8: { title: "Solar Radiation", value: 860, arrowUp: true },
      E9: { title: "Temperature", value: 960, arrowUp: false },
      E10: { title: "Pressure", value: 1060, arrowUp: true },
    },
    {
      id: 8,
      "Deck Name": "Deck 8",
      Boolean: true,
      E1: { title: "Temperature", value: 180, arrowUp: true },
      E2: { title: "Pressure", value: 280, arrowUp: false },
      E3: { title: "Humidity", value: 380, arrowUp: true },
      E4: { title: "Wind Speed", value: 480, arrowUp: false },
      E5: { title: "Precipitation", value: 580, arrowUp: true },
      E6: { title: "Visibility", value: 680, arrowUp: false },
      E7: { title: "UV Index", value: 780, arrowUp: true },
      E8: { title: "Solar Radiation", value: 880, arrowUp: false },
      E9: { title: "Temperature", value: 980, arrowUp: true },
      E10: { title: "Pressure", value: 1080, arrowUp: false },
    },
    {
      id: 9,
      "Deck Name": "Deck 9",
      Boolean: false,
      E1: { title: "Temperature", value: 200, arrowUp: false },
      E2: { title: "Pressure", value: 300, arrowUp: true },
      E3: { title: "Humidity", value: 400, arrowUp: false },
      E4: { title: "Wind Speed", value: 500, arrowUp: true },
      E5: { title: "Precipitation", value: 600, arrowUp: false },
      E6: { title: "Visibility", value: 700, arrowUp: true },
      E7: { title: "UV Index", value: 800, arrowUp: false },
      E8: { title: "Solar Radiation", value: 900, arrowUp: true },
      E9: { title: "Temperature", value: 1000, arrowUp: false },
      E10: { title: "Pressure", value: 1100, arrowUp: true },
    },
    {
      id: 10,
      "Deck Name": "Deck 10",
      Boolean: true,
      E1: { title: "Temperature", value: 120, arrowUp: true },
      E2: { title: "Pressure", value: 220, arrowUp: false },
      E3: { title: "Humidity", value: 320, arrowUp: true },
      E4: { title: "Wind Speed", value: 420, arrowUp: false },
      E5: { title: "Precipitation", value: 520, arrowUp: true },
      E6: { title: "Visibility", value: 620, arrowUp: false },
      E7: { title: "UV Index", value: 720, arrowUp: true },
      E8: { title: "Solar Radiation", value: 820, arrowUp: false },
      E9: { title: "Temperature", value: 920, arrowUp: true },
      E10: { title: "Pressure", value: 1020, arrowUp: false },
    },
    {
      id: 11,
      "Deck Name": "Deck 11",
      Boolean: false,
      E1: { title: "Temperature", value: 140, arrowUp: false },
      E2: { title: "Pressure", value: 240, arrowUp: true },
      E3: { title: "Humidity", value: 340, arrowUp: false },
      E4: { title: "Wind Speed", value: 440, arrowUp: true },
      E5: { title: "Precipitation", value: 540, arrowUp: false },
      E6: { title: "Visibility", value: 640, arrowUp: true },
      E7: { title: "UV Index", value: 740, arrowUp: false },
      E8: { title: "Solar Radiation", value: 840, arrowUp: true },
      E9: { title: "Temperature", value: 940, arrowUp: false },
      E10: { title: "Pressure", value: 1040, arrowUp: true },
    },
    {
      id: 12,
      "Deck Name": "Deck 12",
      Boolean: true,
      E1: { title: "Temperature", value: 160, arrowUp: true },
      E2: { title: "Pressure", value: 260, arrowUp: false },
      E3: { title: "Humidity", value: 360, arrowUp: true },
      E4: { title: "Wind Speed", value: 460, arrowUp: false },
      E5: { title: "Precipitation", value: 560, arrowUp: true },
      E6: { title: "Visibility", value: 660, arrowUp: false },
      E7: { title: "UV Index", value: 760, arrowUp: true },
      E8: { title: "Solar Radiation", value: 860, arrowUp: false },
      E9: { title: "Temperature", value: 960, arrowUp: true },
      E10: { title: "Pressure", value: 1060, arrowUp: false },
    },
    {
      id: 13,
      "Deck Name": "Deck 13",
      Boolean: false,
      E1: { title: "Temperature", value: 180, arrowUp: false },
      E2: { title: "Pressure", value: 280, arrowUp: true },
      E3: { title: "Humidity", value: 380, arrowUp: false },
      E4: { title: "Wind Speed", value: 480, arrowUp: true },
      E5: { title: "Precipitation", value: 580, arrowUp: false },
      E6: { title: "Visibility", value: 680, arrowUp: true },
      E7: { title: "UV Index", value: 780, arrowUp: false },
      E8: { title: "Solar Radiation", value: 880, arrowUp: true },
      E9: { title: "Temperature", value: 980, arrowUp: false },
      E10: { title: "Pressure", value: 1080, arrowUp: true },
    },
    {
      id: 14,
      "Deck Name": "Deck 14",
      Boolean: true,
      E1: { title: "Temperature", value: 200, arrowUp: true },
      E2: { title: "Pressure", value: 300, arrowUp: false },
      E3: { title: "Humidity", value: 400, arrowUp: true },
      E4: { title: "Wind Speed", value: 500, arrowUp: false },
      E5: { title: "Precipitation", value: 600, arrowUp: true },
      E6: { title: "Visibility", value: 700, arrowUp: false },
      E7: { title: "UV Index", value: 800, arrowUp: true },
      E8: { title: "Solar Radiation", value: 900, arrowUp: false },
      E9: { title: "Temperature", value: 1000, arrowUp: true },
      E10: { title: "Pressure", value: 1100, arrowUp: false },
    },
    {
      id: 15,
      "Deck Name": "Deck 15",
      Boolean: false,
      E1: { title: "Temperature", value: 120, arrowUp: false },
      E2: { title: "Pressure", value: 220, arrowUp: true },
      E3: { title: "Humidity", value: 320, arrowUp: false },
      E4: { title: "Wind Speed", value: 420, arrowUp: true },
      E5: { title: "Precipitation", value: 520, arrowUp: false },
      E6: { title: "Visibility", value: 620, arrowUp: true },
      E7: { title: "UV Index", value: 720, arrowUp: false },
      E8: { title: "Solar Radiation", value: 820, arrowUp: true },
      E9: { title: "Temperature", value: 920, arrowUp: false },
      E10: { title: "Pressure", value: 1020, arrowUp: true },
    },
    {
      id: 16,
      "Deck Name": "Deck 16",
      Boolean: true,
      E1: { title: "Temperature", value: 140, arrowUp: true },
      E2: { title: "Pressure", value: 240, arrowUp: false },
      E3: { title: "Humidity", value: 340, arrowUp: true },
      E4: { title: "Wind Speed", value: 440, arrowUp: false },
      E5: { title: "Precipitation", value: 540, arrowUp: true },
      E6: { title: "Visibility", value: 640, arrowUp: false },
      E7: { title: "UV Index", value: 740, arrowUp: true },
      E8: { title: "Solar Radiation", value: 840, arrowUp: false },
      E9: { title: "Temperature", value: 940, arrowUp: true },
      E10: { title: "Pressure", value: 1040, arrowUp: false },
    },
    {
      id: 17,
      "Deck Name": "Deck 17",
      Boolean: false,
      E1: { title: "Temperature", value: 160, arrowUp: false },
      E2: { title: "Pressure", value: 260, arrowUp: true },
      E3: { title: "Humidity", value: 360, arrowUp: false },
      E4: { title: "Wind Speed", value: 460, arrowUp: true },
      E5: { title: "Precipitation", value: 560, arrowUp: false },
      E6: { title: "Visibility", value: 660, arrowUp: true },
      E7: { title: "UV Index", value: 760, arrowUp: false },
      E8: { title: "Solar Radiation", value: 860, arrowUp: true },
      E9: { title: "Temperature", value: 960, arrowUp: false },
      E10: { title: "Pressure", value: 1060, arrowUp: true },
    },
    {
      id: 18,
      "Deck Name": "Deck 18",
      Boolean: true,
      E1: { title: "Temperature", value: 180, arrowUp: true },
      E2: { title: "Pressure", value: 280, arrowUp: false },
      E3: { title: "Humidity", value: 380, arrowUp: true },
      E4: { title: "Wind Speed", value: 480, arrowUp: false },
      E5: { title: "Precipitation", value: 580, arrowUp: true },
      E6: { title: "Visibility", value: 680, arrowUp: false },
      E7: { title: "UV Index", value: 780, arrowUp: true },
      E8: { title: "Solar Radiation", value: 880, arrowUp: false },
      E9: { title: "Temperature", value: 980, arrowUp: true },
      E10: { title: "Pressure", value: 1080, arrowUp: false },
    },
    {
      id: 19,
      "Deck Name": "Deck 19",
      Boolean: false,
      E1: { title: "Temperature", value: 200, arrowUp: false },
      E2: { title: "Pressure", value: 300, arrowUp: true },
      E3: { title: "Humidity", value: 400, arrowUp: false },
      E4: { title: "Wind Speed", value: 500, arrowUp: true },
      E5: { title: "Precipitation", value: 600, arrowUp: false },
      E6: { title: "Visibility", value: 700, arrowUp: true },
      E7: { title: "UV Index", value: 800, arrowUp: false },
      E8: { title: "Solar Radiation", value: 900, arrowUp: true },
      E9: { title: "Temperature", value: 1000, arrowUp: false },
      E10: { title: "Pressure", value: 1100, arrowUp: true },
    },
    {
      id: 20,
      "Deck Name": "Deck 20",
      Boolean: true,
      E1: { title: "Temperature", value: 220, arrowUp: true },
      E2: { title: "Pressure", value: 320, arrowUp: false },
      E3: { title: "Humidity", value: 420, arrowUp: true },
      E4: { title: "Wind Speed", value: 520, arrowUp: false },
      E5: { title: "Precipitation", value: 620, arrowUp: true },
      E6: { title: "Visibility", value: 720, arrowUp: false },
      E7: { title: "UV Index", value: 820, arrowUp: true },
      E8: { title: "Solar Radiation", value: 920, arrowUp: false },
      E9: { title: "Temperature", value: 1020, arrowUp: true },
      E10: { title: "Pressure", value: 1120, arrowUp: false },
    },
  ];

  return (
    <div className="">
      <div className="flex justify-between">
        <h1 className="text-2xl font-semibold mb-4 flex justify-center md:justify-start  dark:bg-black dark:text-purple-50 ">
          Decks
        </h1>
      </div>

      <div className="border border-gray-200">
        <Table headers={headers} data={data} />
      </div>
    </div>
  );
};

export default page;
