-- AlterTable
ALTER TABLE "Deck" ALTER COLUMN "deck_name" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Element" ALTER COLUMN "element_name" SET DATA TYPE TEXT,
ALTER COLUMN "element_operator" SET DATA TYPE TEXT,
ALTER COLUMN "element_value" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "username" SET DATA TYPE TEXT,
ALTER COLUMN "password" SET DATA TYPE TEXT,
ALTER COLUMN "email" SET DATA TYPE TEXT,
ALTER COLUMN "unit_system" SET DATA TYPE TEXT,
ALTER COLUMN "role" SET DATA TYPE TEXT;
