import { NextResponse } from "next/server";
import pool from "../../../lib/db"; // Your database connection file

// POST request to save deck
export async function POST(req: Request) {
  try {
    const { deckName, deckStatus, userId } = await req.json(); // Get the deck data from the request

    if (!deckName || !deckStatus || !userId) {
      return NextResponse.json(
        {
          success: false,
          message: "Deck name, status, and user ID are required",
        },
        { status: 400 }
      );
    }

    // Insert the new deck into the database. deck_id is auto-generated by PostgreSQL.
    const result = await pool.query(
      `INSERT INTO decks (deck_name, deck_status, user_id) 
       VALUES ($1, $2, $3)`,
      [deckName, deckStatus, userId]
    );

    const newDeck = result.rows[0];

    return NextResponse.json(
      { success: true, message: "Deck saved successfully!", deck: newDeck },
      { status: 200 }
    );
  } catch (error) {
    console.error("Error saving deck:", error);
    return NextResponse.json(
      { success: false, message: "Internal server error" },
      { status: 500 }
    );
  }
}
